#cloud-config

timezone: "America/Sao_Paulo"

users:
  - name: sysadmin
    gecos: "Sys Admin"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: sudo
    lock_passwd: false
    passwd: '$6$rounds=4096$JF4SX9YzUXHAJFzK$jT/9HCx4whsvxQSnunrwAKpGYC21UytrT0pa9Z9W0kdXVozwdLUp5aLhd/atQFodDCi2p0is9V67qOPKDGsTw.'
    
packages:
  - curl
  - net-tools
  - postgresql 
  - postgresql-contrib
  - postgresql-client

runcmd:
  - sudo apt update
  - wget ./ssh/60-cloudimg-settings.conf -O /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
  - service ssh restart
  - sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'admin@2024';"
  - systemctl enable postgresql
  - systemctl start postgresql
  - sudo -u postgres psql -c "CREATE DATABASE cs_base;"

  # - mkdir -p /etc/netplan
  # - wget 01-netcfg.yaml -O /etc/netplan/01-netcfg.yaml
  # - chmod 644 /etc/netplan/01-netcfg.yaml
  # - netplan apply

